# Generated by Django 4.0.4 on 2022-04-27 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='title',
            field=models.CharField(choices=[('Mr.', 'Mr.'), ('Mrs.', 'Mrs.')], default=('Mr.', 'Mr.'), max_length=4),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='function',
            field=models.CharField(choices=[('Administrative', 'Administrative'), ('Academic', 'Academic'), ('Physique', 'Physique')], max_length=150),
        ),
    ]
