# Generated by Django 4.0.4 on 2022-04-27 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_teacher_title_alter_teacher_function'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='date_employed',
            new_name='date_created',
        ),
    ]
