# Generated by Django 4.0.4 on 2022-06-16 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatarr',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='account_balance',
            field=models.CharField(blank=True, default='$0', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='total_deposit',
            field=models.CharField(blank=True, default='$0', max_length=50, null=True),
        ),
    ]
