# Generated by Django 4.0.4 on 2022-06-16 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_avatarr_user_gender_alter_user_account_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, default=('Male', 'Male'), max_length=20, null=True),
        ),
    ]
