# Generated by Django 4.0.4 on 2022-06-19 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_user_percentage_alter_user_total_deposit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='percentage',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
