# Generated by Django 4.0.4 on 2022-07-01 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_alter_user_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='referral',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
