# Generated by Django 4.0.4 on 2022-04-16 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pupil',
            name='Class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.class'),
        ),
        migrations.AlterField(
            model_name='pupil',
            name='passport',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='staff',
            name='passport',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='passport',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
