# Generated by Django 4.0.4 on 2022-04-30 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date_of_birth', models.DateTimeField()),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default=('M', 'Male'), max_length=2)),
                ('phone_number', models.CharField(max_length=15)),
                ('email_address', models.EmailField(blank=True, max_length=254, null=True)),
                ('avatar', models.ImageField(upload_to='')),
                ('address', models.TextField()),
            ],
        ),
    ]
