# Generated by Django 4.0.4 on 2022-06-18 18:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_payment_date_created_alter_payment_receipt_withdraw'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdraw',
            name='date_created',
            field=models.CharField(default=django.utils.timezone.now, max_length=40),
        ),
        migrations.AlterField(
            model_name='payment',
            name='date_created',
            field=models.CharField(default=django.utils.timezone.now, max_length=40),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date_created',
            field=models.CharField(default=django.utils.timezone.now, max_length=40),
        ),
    ]
