# Generated by Django 4.0.4 on 2022-04-30 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('budget', models.FloatField()),
                ('status', models.CharField(choices=[('Not started', 'Not started'), ('Working', 'Working'), ('Done', 'Done'), ('Canceled', 'Canceled')], default=('Not started', 'Not started'), max_length=30)),
                ('completion', models.CharField(choices=[('0', '0'), ('10', '10'), ('20', '20'), ('30', '30'), ('40', '40'), ('50', '50'), ('60', '60'), ('70', '70'), ('80', '80'), ('90', '90'), ('100', '100')], default=('0', '0'), max_length=30)),
                ('date_created', models.DateField(auto_now=True)),
            ],
        ),
    ]
