# Generated by Django 4.0.4 on 2022-06-18 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_withdraw_date_created_alter_payment_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
