# Generated by Django 4.0.4 on 2022-04-15 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pupil',
            name='passport',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='passport',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
