# Generated by Django 4.0.4 on 2022-04-15 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='role',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=20, null=True),
        ),
    ]
