# Generated by Django 4.0.4 on 2022-06-21 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_transaction_completion_topup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-date_created']},
        ),
    ]
