# Generated by Django 4.0.4 on 2022-07-01 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_transaction_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='withdraw',
            name='btc_wallet_address',
        ),
        migrations.AddField(
            model_name='withdraw',
            name='crypto_id',
            field=models.CharField(choices=[('Bitcoin', 'Bitcoin'), ('Ethereum', 'Ethereum')], default=('Bitcoin', 'Bitcoin'), max_length=50),
        ),
        migrations.AddField(
            model_name='withdraw',
            name='plan',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.plan'),
        ),
        migrations.AddField(
            model_name='withdraw',
            name='wallet_address',
            field=models.TextField(default=''),
        ),
    ]
