# Generated by Django 4.0.4 on 2022-04-15 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_staff_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.CharField(choices=[('CLEANING', 'CLEANING'), ('SECURITY', 'SECURITY'), ('ADMINISTRATIVE', 'ADMINISTRATIVE')], max_length=20, null=True),
        ),
    ]
