# Generated by Django 4.0.4 on 2022-07-01 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_withdraw_btc_wallet_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='withdraw',
            name='plan',
        ),
    ]
