# Generated by Django 4.0.4 on 2022-04-15 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_staff_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='pupil',
            name='Class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.class'),
        ),
    ]
