# Generated by Django 4.0.4 on 2022-04-15 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_pupil_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pupil',
            name='passport',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/pupil'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='passport',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/staff'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='passport',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/teacher'),
        ),
    ]
