# Generated by Django 4.0.4 on 2022-07-07 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_transaction_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdraw',
            name='plan',
            field=models.CharField(choices=[('Bronze Plan', 'Bronze Plan'), ('Silver Plan', 'Silver Plan'), ('Gold Plan', 'Gold Plan'), ('Platinum Plan', 'Platinum Plan')], default=('Bronze Plan', 'Bronze Plan'), max_length=50),
        ),
    ]
