# Generated by Django 4.0.4 on 2022-07-07 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_withdraw_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='withdraw',
            name='plan',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Done', 'Done'), ('Cancelled', 'Cancelled')], default=('Pending', 'Pending'), max_length=30),
        ),
    ]
