# Generated by Django 4.0.4 on 2022-07-07 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_withdraw_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdraw',
            name='plan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.plan'),
        ),
    ]
