# Generated by Django 4.0.4 on 2022-07-08 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_withdraw_plan_alter_transaction_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='duration',
            field=models.CharField(choices=[('1', 'a month'), ('2', '2 months'), ('3', '3 months'), ('4', '4 months'), ('5', '5 months'), ('6', '6 months'), ('7', '7 months'), ('8', '8 months'), ('9', '9 months'), ('10', '10 months'), ('11', '11 months'), ('12', 'a year')], default=('1', 'a month'), max_length=50),
        ),
    ]
