# Generated by Django 4.0.4 on 2022-04-18 23:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('time', models.DateTimeField()),
                ('created_at', models.DateTimeField(default=datetime.datetime(2022, 4, 18, 23, 5, 23, 539031, tzinfo=utc))),
            ],
        ),
    ]
